#!/bin/bash
echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║               SPEISEPLANER SERVICE STATUS                            ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
echo ""
echo "🔍 Backend Service:"
sudo systemctl status speiseplaner-backend.service --no-pager | grep -E "(Active|Main PID)"
echo ""
echo "🔍 Frontend Service:"
sudo systemctl status speiseplaner-frontend.service --no-pager | grep -E "(Active|Main PID)"
echo ""
echo "🌐 Network Ports:"
netstat -tuln | grep -E ":(3000|8001)" || echo "   ⚠️  Ports not listening"
echo ""
echo "📡 Access URLs:"
LOCAL_IP=$(hostname -I | awk '{print $1}')
echo "   Frontend: http://$LOCAL_IP:3000"
echo "   Backend:  http://$LOCAL_IP:8001/api/"
echo ""
